version: '3.3'

volumes:
  postgres:

services:
  postgres:
    image: postgres:10.4-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  clair:
    image: quay.io/coreos/clair:v2.0.6
    restart: unless-stopped
    ports:
      - 6060:6060
      - 6061:6061
    depends_on:
      - postgres
    volumes:
      - ./clair_config:/config
    command: [-config, /config/config.yml]

  scanner:
    build: ./clair-scanner
    image: clair-scanner
    tty: true
    environment:
      CLAIR: http://clair:6060
      SCANNER: 172.17.0.1
    privileged: true
    ports:
      - 9279:9279
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
